# Generated by Django 2.1.3 on 2018-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirQualityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('zipcode', models.CharField(max_length=5)),
                ('pm', models.FloatField()),
                ('stamp', models.DateField()),
            ],
        ),
    ]
