# Generated by Django 2.1.3 on 2018-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirQualityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pm', models.FloatField()),
                ('ozone', models.FloatField()),
                ('stamp', models.DateField()),
            ],
        ),
    ]
